version: "4.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./app/backend:/app
    environment:
      - ENVIRONMENT=development
      - RELOAD=True
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
